import './globals.css'
import { Inter,Ubuntu } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'AiChat',
  description: 'Generated by create next app'
}
const ubuntu=Ubuntu({
  subsets:['latin'],
  weight:['400']

})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  )
}
